version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - target: 4200
        published: 4200
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: npm run start:dev
